name: Build and Commit RSS feed.xml

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2:00 AM (UTC)
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run feed builder
        run: php build-feed.php

      - name: Commit and push updated feed.xml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git commit -m "📰 Auto-update RSS feed.xml ($(date))" || echo "No changes to commit"
          git push
