name: Build feed & site
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Build merged feed
        run: php build-feed.php
        env:
          SITE_ORIGIN: https://pinoytechfeed.pages.dev
      - name: Build site pages + rewrite feed.xml
        run: php build-site.php
        env:
          SITE_ORIGIN: https://pinoytechfeed.pages.dev
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "build: feed & site" || echo "no changes"
          git push