name: Build feed and site
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with: { php-version: '8.2' }
      - name: Build feed & site
        env:
          SITE_ORIGIN: https://pinoytechfeed.pages.dev
        run: |
          php build-feed.php
          php build-site.php
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add feed.xml p/
          git commit -m "Build feed+site" || echo "No changes"
          git push