name: Build & Commit RSS feed.xml

on:
  schedule:
    - cron: "0 2 * * *"   # Every day at 02:00 UTC
  workflow_dispatch:
  push:
    paths:
      - "build-feed.php"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Build feed.xml
        run: php build-feed.php

      - name: Commit feed.xml if changed
        run: |
          if ! git diff --quiet -- feed.xml; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add feed.xml
            git commit -m "chore: update feed.xml [skip ci]"
            git push
          else
            echo "No changes in feed.xml"
          fi
