name: Build feed & site
on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Build feed
        run: php build-feed.php
        env:
          SITE_ORIGIN: https://pinoytechfeed.pages.dev
      - name: Build site pages
        run: php build-site.php
        env:
          SITE_ORIGIN: https://pinoytechfeed.pages.dev
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "Build feed & site"
      - name: Push
        if: success()
        run: git push