name: Build feed & site
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Build feed.xml
        run: php build-feed.php

      - name: Build /p pages
        env:
          SITE_ORIGIN: https://pinoytechfeed.pages.dev
        run: php build-site.php

      - name: Commit generated files
        run: |
          git config user.name  "ptf-bot"
          git config user.email "ptf-bot@users.noreply.github.com"
          git add feed.xml p/
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: build feed & site"
            git push
          fi
